/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/shared/Header.vue')['default']
    Navigation: typeof import('./src/components/shared/Navigation.vue')['default']
    QuestList: typeof import('./src/components/quest/QuestList.vue')['default']
    QuestTile: typeof import('./src/components/quest/QuestTile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
